version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  health-orchestrator:
    build: .
    volumes:
      - .:/app
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090