high_availability:
  # Load balancing
  load_balancer:
    enabled: true
    algorithm: "round_robin"  # Options: round_robin, least_connections, ip_hash
    health_check_interval: 30
    unhealthy_threshold: 3
    healthy_threshold: 2
  
  # Clustering
  cluster:
    enabled: true
    mode: "active-passive"  # Options: active-passive, active-active
    election_timeout: 30
    heartbeat_interval: 10
    sync_interval: 60
  
  # Failover
  failover:
    enabled: true
    detection_interval: 15
    recovery_timeout: 300
    max_retries: 3
  
  # Data replication
  replication:
    enabled: true
    replicas: 2
    sync_mode: "async"  # Options: sync, async
    backup_interval: 3600  # 1 hour