performance:
  # Async processing
  async_workers: 4
  thread_pool_size: 10
  connection_pool_size: 20
  
  # Caching
  cache:
    enabled: true
    ttl: 300  # 5 minutes
    max_size: 1000
    backend: "memory"  # Options: memory, redis
  
  # Batch processing
  batch_processing:
    enabled: true
    batch_size: 100
    flush_interval: 30  # seconds
    max_queue_size: 1000
  
  # Resource limits
  limits:
    max_memory_mb: 1024
    max_cpu_percent: 80
    max_file_descriptors: 1024
    max_concurrent_requests: 50
  
  # Garbage collection
  gc:
    enabled: true
    interval: 300  # seconds
    threshold: 700  # objects