apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-orchestrator-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - health-orchestrator.company.com
    secretName: health-orchestrator-tls
  rules:
  - host: health-orchestrator.company.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: health-orchestrator
            port:
              number: 8080